### PR TITLE
Proposal for encapsulating requests errors and provide user option for verifing ssl certs

### PR DESCRIPTION
**Pull request by dlm**
The original goal was to all the user to specify an option for verifying ssl certs.   (relevant to issue #16)

In the process, I ended up encapsulating the requests errors within itunes-iap.

### CODE REVIEW

**Comment by youknowone** [comment]
The pull request is not merged but I've rebased your commits a little and merged: https://github.com/youknowone/itunes-iap/commit/1a6eb3a381329a009d4a78ecd588dd6956de0da8

**Comment by youknowone** [comment]
I like the idea of `verify_request` but i also thought it can be a little bit unclear what it means.
I changed the name to `verify_ssl` and put it into environments.
Also, I changed the default value to 'YES' which will be covered by requests[security] dependency.

**Comment by dlm** [comment]
Awesome!! Thank you!!  This collection of projects was tons of fun to work on!  Please let me know if there is anything I can do to help with anything else.

**Comment by youknowone** [comment]
Recently I am interested in collecting fragmented patches from forks of this project which is roughly merged to v1 between 0.6.6 ~ 0.7.0 `https://github.com/youknowone/itunes-iap/tree/v1`, especially about test cases.
I think next release will be with this work.

I am happy to work with you and your patches :D

**Pull request closed without merging**
