### PR TITLE
Allows access iTunes Validation URL through proxy 

### PR DESCRIPTION
**Pull request by marinampires**
In my work environments the server has no internet access, so is necessary to access external urls with proxy.

### CODE REVIEW

**Comment by youknowone** [comment]
Thanks for a nice patch. I learn about proxies in `requests` due to your patch.

Here is a suggestion:
If we should attach `https://` internally, than how about just get the full URL from users including `https://`?
like:
```
protocol = self.proxy_url.split('://')[0]

**Comment by marinampires** [comment]
@youknowone, I made the changes that you suggested.
Could you take a look? 84c289e

**Comment by youknowone** [comment]
Looks good for me. Thanks!

**Comment by youknowone** [comment]
Released: https://pypi.python.org/pypi/itunes-iap/2.2.0

**Comment by marinampires** [comment]
Thanks ;)

**Pull request merged**
