### PR TITLE
Proposed bugfix for calling response.receipt.in_app resulting in an error

### PR DESCRIPTION
**Pull request by dlm**
This pull request provides a proposed solution for calling response.receipt.in_app in the new receipt format.  It also produces a uniform return type for python2 and python3

### CODE REVIEW

**Comment by youknowone** [comment]
Thanks! I can't believe there is this kind of obvious problem.
It is released as 2.0.1.

**Comment by dlm** [comment]
Glad to help.  Thank you for making such a great tool!  

One other question (which I now realize that I should have asked before issuing the pull request).  Since in_app is part of the new format only , should it be in __WHITELIST__?

**Comment by youknowone** [comment]
Yep, it must be, exactly!

**Comment by dlm** [comment]
would you like to me to add?

**Comment by youknowone** [comment]
If you don't mind :D

**Comment by dlm** [comment]
new pull request underway.

**Pull request merged**
